export const ALIGN_RENDERED_SOURCE_TOKEN = 'WA::ALIGN_RENDERED_SOURCE_TOKEN';
export const UNALIGN_RENDERED_SOURCE_TOKEN = 'WA::UNALIGN_RENDERED_SOURCE_TOKEN';
export const INSERT_RENDERED_ALIGNMENT = 'WA::INSERT_RENDERED_ALIGNMENT';
export const ALIGN_RENDERED_TARGET_TOKEN = 'WA::ALIGN_RENDERED_TARGET_TOKEN';
export const UNALIGN_RENDERED_TARGET_TOKEN = 'WA::UNALIGN_RENDERED_TARGET_TOKEN';
export const SET_CHAPTER_ALIGNMENTS = 'WA::SET_CHAPTER_ALIGNMENTS';
export const SET_SOURCE_TOKENS = 'WA::SET_SOURCE_TOKENS';
export const SET_TARGET_TOKENS = 'WA::SET_TARGET_TOKENS';
export const CLEAR_STATE = 'WA::CLEAR_STATE';
export const RESET_VERSE_ALIGNMENTS = 'WA::RESET_VERSE_ALIGNMENTS';
export const REPAIR_VERSE_ALIGNMENTS = 'WA::REPAIR_VERSE_ALIGNMENTS';
export const SET_ALIGNMENT_SUGGESTIONS = 'WA::SET_ALIGNMENT_SUGGESTIONS';
export const RESET_VERSE_ALIGNMENT_SUGGESTIONS = 'WA::RESET_VERSE_ALIGNMENT_SUGGESTIONS';
export const ACCEPT_VERSE_ALIGNMENT_SUGGESTIONS = 'WA::ACCEPT_VERSE_ALIGNMENT_SUGGESTIONS';
export const REMOVE_TOKEN_SUGGESTION = 'WA::REMOVE_TOKEN_SUGGESTION';
export const ACCEPT_TOKEN_SUGGESTION = 'WA::ACCEPT_TOKEN_SUGGESTION';
export const RECORD_CHECK = 'WA::RECORD_CHECK';
export const CLEAR_GROUP_MENU = 'WA::CLEAR_GROUP_MENU';
export const SET_GROUP_MENU_FINISHED = 'WA::SET_GROUP_MENU_FINISHED';
export const SET_GROUP_MENU_INVALID = 'WA::SET_GROUP_MENU_INVALID';
export const SET_GROUP_MENU_UNALIGNED = 'WA::SET_GROUP_MENU_UNALIGNED';
export const SET_GROUP_MENU_EDITED = 'WA::SET_GROUP_MENU_EDITED';
export const SET_GROUP_MENU_BOOKMARKED = 'WA::SET_GROUP_MENU_BOOKMARKED';
export const SET_GROUP_MENU_COMMENT = 'WA::SET_GROUP_MENU_COMMENT';
export const SET_GROUP_MENU_STATE = 'WA::SET_GROUP_MENU_STATE';
export const ADD_COMMENT = 'WA::ADD_COMMENT';
export const LOAD_COMMENT = 'WA::LOAD_COMMENT';
export const LOAD_REMINDER = 'WA::LOAD_REMINDER';

export const SET_FINISHED = 'WA::SET_FINISHED';
export const SET_INVALID = 'WA::SET_INVALID';
export const SET_UNALIGNED = 'WA::SET_UNALIGNED';
export const SET_EDITED = 'WA::SET_EDITED';
export const SET_BOOKMARKED = 'WA::SET_BOOKMARKED';
export const SET_COMMENT = 'WA::SET_COMMENT';
export const SET_STATE = 'WA::SET_STATE';
// groupsDataReducer
export const CLEAR_PREVIOUS_GROUPS_DATA = 'WA::CLEAR_PREVIOUS_GROUPS_DATA';
export const LOAD_GROUPS_DATA_FROM_FS = 'WA::LOAD_GROUPS_DATA_FROM_FS';
// groupsIndexReducer
export const LOAD_GROUPS_INDEX = 'WA::LOAD_GROUPS_INDEX';
export const UPDATE_REFRESH_COUNT_GROUPS_INDEX = 'WA::UPDATE_REFRESH_COUNT_GROUPS_INDEX';
export const CLEAR_PREVIOUS_GROUPS_INDEX = 'WA::CLEAR_PREVIOUS_GROUPS_INDEX';
// contextIdReducer
export const CHANGE_CONTEXT_ID = 'WA::CHANGE_CONTEXT_ID';
export const CLEAR_CONTEXT_ID = 'WA::CLEAR_CONTEXT_ID';
// groupMenuReducer
export const GROUP_MENU_EXPAND_SUBMENU = 'WA::GROUP_MENU_EXPAND_SUBMENU';
export const TOGGLE_MENU_DRAWER = 'WA::TOGGLE_MENU_DRAWER';
export const GROUP_MENU_SET_FILTER = 'WA::GROUP_MENU_SET_FILTER';
export const CLEAR_PREVIOUS_FILTERS = 'WA::CLEAR_PREVIOUS_FILTERS';
// bookmarksReducer
export const ADD_BOOKMARK = 'WA::ADD_BOOKMARK';
// selectionsReducer
export const CHANGE_SELECTIONS = 'TOOL::CHANGE_SELECTIONS';
export const TOGGLE_SELECTIONS_IN_GROUPDATA = 'TOOL::TOGGLE_SELECTIONS_IN_GROUPDATA';
export const SET_INVALIDATION_IN_GROUPDATA = 'TOOL::SET_INVALIDATION_IN_GROUPDATA';
