export const ALIGN_SOURCE_TOKEN = 'ALIGN_SOURCE_TOKEN';
export const UNALIGN_SOURCE_TOKEN = 'UNALIGN_SOURCE_TOKEN';
export const ALIGN_TARGET_TOKEN = 'ALIGN_TARGET_TOKEN';
export const UNALIGN_TARGET_TOKEN = 'UNALIGN_TARGET_TOKEN';
export const SET_CHAPTER_ALIGNMENTS = 'SET_CHAPTER_ALIGNMENTS';
