export const ALIGN_RENDERED_SOURCE_TOKEN = 'ALIGN_RENDERED_SOURCE_TOKEN';
export const UNALIGN_RENDERED_SOURCE_TOKEN = 'UNALIGN_RENDERED_SOURCE_TOKEN';
export const INSERT_RENDERED_ALIGNMENT = 'INSERT_RENDERED_ALIGNMENT';
/**
 * @deprecated
 * @type {string}
 */
export const MOVE_RENDERED_SOURCE_TOKEN = 'MOVE_SOURCE_TOKEN';

export const ALIGN_RENDERED_TARGET_TOKEN = 'ALIGN_RENDERED_TARGET_TOKEN';
export const UNALIGN_RENDERED_TARGET_TOKEN = 'UNALIGN_RENDERED_TARGET_TOKEN';

export const SET_CHAPTER_ALIGNMENTS = 'SET_CHAPTER_ALIGNMENTS';
export const SET_SOURCE_TOKENS = 'SET_SOURCE_TOKENS';
export const SET_TARGET_TOKENS = 'SET_TARGET_TOKENS';
export const CLEAR_STATE = 'CLEAR_STATE';
export const RESET_VERSE_ALIGNMENTS = 'RESET_VERSE_ALIGNMENTS';
export const REPAIR_VERSE_ALIGNMENTS = 'REPAIR_VERSE_ALIGNMENTS';
export const SET_ALIGNMENT_SUGGESTIONS = 'SET_ALIGNMENT_SUGGESTIONS';
export const RESET_VERSE_ALIGNMENT_SUGGESTIONS = 'RESET_VERSE_ALIGNMENT_SUGGESTIONS';
export const ACCEPT_VERSE_ALIGNMENT_SUGGESTIONS = 'ACCEPT_VERSE_ALIGNMENT_SUGGESTIONS';
